platform: linux

image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task

inputs:
  - name: package

outputs:
  - name: image

params:
  CONTEXT: package

run:
  path: build