platform: linux

image_resource:
  type: docker-image
  source: 
    repository: snyk/snyk-cli
    tag: maven-3.5.4

inputs:
  - name: git
  - name: version

caches:
  - path: maven

params:
  SNYK_TOKEN: token
  MONITOR: false
  EXEC_PATH: git/admin
  VERSION_PATH: ../../version/version

run:
  path: sh
  args:
  - -exc
  - |
      export ROOT_FOLDER=$(pwd)
      ln -s "${ROOT_FOLDER}/maven" "${HOME}/.m2"

      cd $EXEC_PATH
      cat $VERSION_PATH
      mvn versions:set -DnewVersion=$(cat $VERSION_PATH) -f pom-admin.xml
      snyk test --org=coats-plc --severity-threshold=medium