platform: linux

image_resource:
  type: docker-image
  source:
    repository: cathive/concourse-sonarqube-qualitygate-task
    tag: 1.0.0

inputs:
  - name: sonarqube

run:
  path: /sonarqube-qualitygate-check
  dir: sonarqube